### PR TITLE
Pressflow 7.35

### PR DESCRIPTION
**Pull request by mparker17**
Merged changes from 7.35, which fixes SA-CORE-2015-001. This is a security update, so expediency is appreciated.

Note I submitted #52 earlier, but that PR is weird because it seems to jump two versions. Dunno what I did wrong.

Commands I used to generate this:

```
git clone --recursive git@github.com:mparker17/7.git && cd 7
git checkout master && git pull --rebase
git remote add drupal http://git.drupal.org/project/drupal.git && git fetch drupal
git remote add upstream https://github.com/pressflow/7.git && git fetch upstream
git merge upstream/master && git push origin master
git checkout -b pressflow-7.35-take-2
git merge 7.35
git push --set-upstream origin pressflow-7.35-take-2
```

Reviews welcome.

### CODE REVIEW

**Comment by fluxsauce** [comment]
No worries. Good to go, thank you!

**Comment by scottatdrake** [comment]
Thanks! Looks like we didn't get a pressflow-7.35 tag, though. Just keeping ya honest! :)

**Comment by fluxsauce** [comment]
Dang it. On it.

**Comment by fluxsauce** [comment]
@scottatdrake https://github.com/pressflow/7/releases/tag/pressflow-7.35

**Pull request merged**
