### PR TITLE
Pressflow 7.39

### PR DESCRIPTION
**Pull request by fluxsauce**
https://github.com/drupal/drupal/commit/be00a1ced4104d84df2f34b149b35fb0adf91093

### CODE REVIEW

**Comment by fluxsauce** [comment]
@mparker17 care to do the honors?

**Comment by mparker17** [comment]
@fluxsauce looks good to me, but I don't have write access to pressflow to merge it! :stuck_out_tongue:

**Comment by joshkoenig** [comment]
:shipit:

**Comment by mparker17** [comment]
Thanks @joshkoenig! :+1:

**Pull request merged**
