### PR TITLE
Newest release: 7.76

### PR DESCRIPTION
**Pull request by fkbender**

### CODE REVIEW

**Comment by gravelpot** [comment]
Looks like @generalredneck is generally who merges these PRs... just curious if this will get looked at soon? Unfortunately, the Pressflow updates hold up the entire Pantheon Drupal 7 upstream process.

**Comment by greg-1-anderson** [comment]
It really should be up to Pantheon to make their deployment process not be dependent on volunteers. There's a card in the backlog for this.

**Comment by generalredneck** [comment]
@gravelpot Thanks for pinging me I didn't realize that a new release went out yesterday. Un Momento!

**Comment by generalredneck** [comment]
@greg-1-anderson @gravelpot , I'm usually on top of it because it's typically security releases... When there's a feature/bugfix release. I sometimes miss them... I'm going to update some CI a bit to ping the team when one of these come up just in case noone is paying attention (and I'm out sick or something)

**Comment by greg-1-anderson** [comment]
Thanks for all that you do @generalredneck, it is much appreciated.

**Pull request merged**
