### PR TITLE
Newest release: 7.91

### PR DESCRIPTION
**Pull request by fkbender**

### CODE REVIEW

**Review by generalredneck — APPROVED** [review]

**Comment by johnpink** [comment]
Hello ! It seems like you didn't add a tag for the latest release 7.90.
Please append a tag 7.91 when you merge this so my auto-deploy script can pick up the latest changes :)
Thanks !

**Comment by generalredneck** [comment]
:scream: 
@johnpink You are so right.
You should be good to go!

https://github.com/pressflow/7/tree/pressflow-7.91

Humans... amiright!?

**Comment by johnpink** [comment]
Thanks for the quick response @generalredneck ! However it seems like you tagged the 7.90 release with 7.91 x) The tag should have been 7.90, keeping 7.91 for when this PR gets merged.
Cheers.

**Comment by macburgee1** [comment]
I can confirm that 7.90 is tagged as 7.91.

**Comment by generalredneck** [comment]
Sorry about the delay. I see I'm screwing up spectacularly. For some reason I though Johnpink was commenting on #107 originally. All excuses at this point obviously.

Ok, let me see if I can salvage this mess. quick question, How do yalls implementation work. Will it work if I force update the 7.91 tag or am I goign to have to do something like 7.91.1. I know for composer implementations... if someone doesn't clear their cache ahead of time... they will get the old commit for the 7.91 tag.

**Comment by generalredneck** [comment]
As an FYI, here's what I did,

I tagged pressflow-7.90 as b02e7273325f2f2152f3fc1e80f1137fbe3801c9. which was the same as pressflow-7.91 at the time.
I then merged in THIS PR (#108) and force pushed a tag to pressflow-7.91.
If you need me to push an alternative presslfow-7.91.1 to counter come CI issues, let me know... but for the time being you should be able to pull in that tag if you do `git fetch origin --tags --force`. This may require a 1 time intervention from you all if you say use jenkins to do these builds.... you know because of workspaces and the git history still existing as opposed to a fresh clone each time.

**Comment by johnpink** [comment]
all good @generalredneck !! thanks for the merge and tag resolution :) +++

**Pull request merged**
